# Generated by Django 6.0.6 on 2026-07-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('need_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('qualified', 'Qualified'), ('sent_to_crm', 'Sent to CRM'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('crm_external_id', models.CharField(blank=True, max_length=120)),
                ('crm_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_to_crm_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_draft', to='conversations.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_drafts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
