# Generated by Django 6.0.6 on 2026-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddraft',
            name='dispatch_status',
            field=models.CharField(choices=[('not_queued', 'Not queued'), ('pending', 'Pending'), ('dry_run', 'Dry run'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='not_queued', max_length=30),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='handoff_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('ready', 'Ready'), ('requested', 'Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_requested', max_length=30),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='qualification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='qualification_policy',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='qualification_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='new', max_length=30),
        ),
    ]
