# Generated by Django 6.0.6 on 2026-09-02 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_commercial_operations'),
        ('leads', '0002_leaddraft_dispatch_status_leaddraft_field_sources_and_more'),
        ('tenants', '0008_assistantprofile_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='commercial_status',
            field=models.CharField(choices=[('new', 'Novo'), ('contact_pending', 'Contato pendente'), ('in_progress', 'Em atendimento'), ('qualified', 'Qualificado'), ('won', 'Ganho'), ('lost', 'Perdido'), ('closed', 'Encerrado')], db_index=True, default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='first_human_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaddraft',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='leaddraft',
            index=models.Index(fields=['tenant', 'commercial_status', '-updated_at'], name='leads_leadd_tenant__e935fd_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddraft',
            index=models.Index(fields=['tenant', 'assigned_to', '-updated_at'], name='leads_leadd_tenant__c3ff21_idx'),
        ),
        migrations.AddField(
            model_name='commercialnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercialnote',
            name='handoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_notes', to='conversations.handoffrequest'),
        ),
        migrations.AddField(
            model_name='commercialnote',
            name='lead_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_notes', to='leads.leaddraft'),
        ),
        migrations.AddField(
            model_name='commercialnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_notes', to='tenants.tenant'),
        ),
    ]
