# Generated by Django 6.0.6 on 2026-07-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_handoffrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='handoffrequest',
            new_name='conversatio_tenant__2b116d_idx',
            old_name='conversation_tenant__53fdfb_idx',
        ),
        migrations.RenameIndex(
            model_name='handoffrequest',
            new_name='conversatio_convers_3908fc_idx',
            old_name='conversation_convers_4b4dd1_idx',
        ),
    ]
