# Generated by Django 6.0.6 on 2026-07-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_rename_conversation_tenant__53fdfb_idx_conversatio_tenant__2b116d_idx_and_more'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=120)),
                ('request_id', models.UUIDField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.PositiveSmallIntegerField(default=200)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_requests', to='conversations.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='conversatio_tenant__185905_idx'), models.Index(fields=['status', 'updated_at'], name='conversatio_status_af6559_idx'), models.Index(fields=['tenant', 'session_id'], name='conversatio_tenant__67ceb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'session_id', 'request_id'), name='unique_chat_request_per_tenant_session_request')],
            },
        ),
    ]
