# Generated by Django 6.0.6 on 2026-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffrequest',
            name='dispatch_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('dry_run', 'Dry run'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='handoffrequest',
            name='handoff_state',
            field=models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
    ]
