# Generated by Django 6.0.6 on 2026-09-02 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_handoffrequest_dispatch_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handoffrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handoffrequest',
            name='first_human_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
