# Generated by Django 6.0.6 on 2026-07-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='tenants.tenant')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_knowledge_document_per_tenant_slug')],
            },
        ),
    ]
