# Generated by Django 6.0.6 on 2026-07-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_document_source_type_tags'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRagConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_folder_id', models.CharField(max_length=120)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('last_inventory_status', models.CharField(choices=[('idle', 'Idle'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_file_count', models.PositiveIntegerField(default=0)),
                ('last_inventory_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_configuration', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug'],
                'indexes': [models.Index(fields=['sync_enabled'], name='knowledge_b_sync_en_4def5c_idx'), models.Index(fields=['last_inventory_status'], name='knowledge_b_last_in_6d6797_idx')],
            },
        ),
    ]
