# Generated by Django 6.0.6 on 2026-07-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_tenantragconfiguration'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_inventory_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_inventory_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantragconfiguration',
            name='last_inventory_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantRagDriveFileManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=160)),
                ('relative_path', models.CharField(blank=True, max_length=600)),
                ('drive_modified_time', models.DateTimeField(blank=True, null=True)),
                ('drive_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('normalized_text_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('exported', 'Exported'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped_unsupported', 'Skipped unsupported'), ('failed', 'Failed'), ('removed', 'Removed'), ('unavailable', 'Unavailable')], default='discovered', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('first_discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_file_manifests', to='knowledge_base.tenantragconfiguration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_drive_file_manifests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'relative_path', 'name', 'drive_file_id'],
            },
        ),
        migrations.CreateModel(
            name='TenantRagDriveTextStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_text', models.TextField(blank=True)),
                ('normalized_text_sha256', models.CharField(max_length=64)),
                ('normalized_text_char_count', models.PositiveIntegerField(default=0)),
                ('normalized_text_byte_count', models.PositiveIntegerField(default=0)),
                ('exported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_staging', to='knowledge_base.tenantragdrivefilemanifest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_drive_text_staging', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantragdrivefilemanifest',
            index=models.Index(fields=['tenant', 'status'], name='knowledge_b_tenant__80ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragdrivefilemanifest',
            index=models.Index(fields=['tenant', 'is_active'], name='knowledge_b_tenant__82b0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragdrivefilemanifest',
            index=models.Index(fields=['tenant', 'last_seen_at'], name='knowledge_b_tenant__06d7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantragdrivefilemanifest',
            constraint=models.UniqueConstraint(fields=('tenant', 'drive_file_id'), name='unique_rag_drive_file_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantragdrivetextstaging',
            index=models.Index(fields=['tenant', 'updated_at'], name='knowledge_b_tenant__81f119_idx'),
        ),
    ]
