# Generated by Django 6.0.6 on 2026-07-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_tenantragconfiguration_last_inventory_mode_and_more'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRagDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('chunk_text', models.TextField(blank=True)),
                ('chunk_sha256', models.CharField(max_length=64)),
                ('source_text_sha256', models.CharField(max_length=64)),
                ('chunk_config_signature', models.CharField(max_length=64)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('byte_count', models.PositiveIntegerField(default=0)),
                ('start_char', models.PositiveIntegerField(default=0)),
                ('end_char', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('failed', 'Failed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.tenantragdrivefilemanifest')),
                ('staging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.tenantragdrivetextstaging')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_document_chunks', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__slug', 'manifest_id', 'ordinal'],
                'indexes': [models.Index(fields=['tenant', 'manifest', 'is_active'], name='knowledge_b_tenant__ccb520_idx'), models.Index(fields=['tenant', 'source_text_sha256'], name='knowledge_b_tenant__776e27_idx'), models.Index(fields=['tenant', 'status'], name='knowledge_b_tenant__53ef3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'manifest', 'source_text_sha256', 'chunk_config_signature', 'ordinal'), name='unique_rag_chunk_per_document_version_ordinal')],
            },
        ),
    ]
