# Generated by Django 6.0.6 on 2026-07-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_tenantragdocumentchunk'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRagChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_sha256', models.CharField(max_length=64)),
                ('chunk_config_signature', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=120)),
                ('dimension', models.PositiveIntegerField()),
                ('embedding_config_signature', models.CharField(max_length=64)),
                ('vector', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('failed', 'Failed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('first_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tenant__slug', 'chunk_id', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRagIndexRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=30)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('dimension', models.PositiveIntegerField(default=0)),
                ('embedding_config_signature', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('documents', models.PositiveIntegerField(default=0)),
                ('chunks', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('indexed', models.PositiveIntegerField(default=0)),
                ('reindexed', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('deactivated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('batches', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_run_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='last_index_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tenantragconfiguration',
            index=models.Index(fields=['last_index_status'], name='knowledge_b_last_in_fc81dd_idx'),
        ),
        migrations.AddField(
            model_name='tenantragchunkembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge_base.tenantragdocumentchunk'),
        ),
        migrations.AddField(
            model_name='tenantragchunkembedding',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='knowledge_base.tenantragdrivefilemanifest'),
        ),
        migrations.AddField(
            model_name='tenantragchunkembedding',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunk_embeddings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantragindexrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_index_runs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantragchunkembedding',
            index=models.Index(fields=['tenant', 'is_active', 'status'], name='knowledge_b_tenant__9fcb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragchunkembedding',
            index=models.Index(fields=['tenant', 'embedding_config_signature'], name='knowledge_b_tenant__9b1e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragchunkembedding',
            index=models.Index(fields=['tenant', 'chunk', 'is_active'], name='knowledge_b_tenant__d168ac_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragchunkembedding',
            index=models.Index(fields=['tenant', 'manifest'], name='knowledge_b_tenant__ddd53d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantragchunkembedding',
            constraint=models.UniqueConstraint(fields=('tenant', 'chunk', 'embedding_config_signature'), name='unique_rag_embedding_per_chunk_config'),
        ),
        migrations.AddIndex(
            model_name='tenantragindexrun',
            index=models.Index(fields=['tenant', 'status'], name='knowledge_b_tenant__e53dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantragindexrun',
            index=models.Index(fields=['tenant', 'started_at'], name='knowledge_b_tenant__2b7cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantragindexrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'run_id'), name='unique_rag_index_run_per_tenant'),
        ),
    ]
