# Generated by Django 6.0.6 on 2026-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_tenantragchunkembedding_and_indexrun'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='retrieval_enabled',
            field=models.BooleanField(default=False, help_text='Permite recuperação semântica no fluxo de conversa deste tenant.'),
        ),
        migrations.AddIndex(
            model_name='tenantragconfiguration',
            index=models.Index(fields=['retrieval_enabled'], name='knowledge_b_retriev_9a480d_idx'),
        ),
    ]
