# Generated by Django 6.0.6 on 2026-07-29 18:10

import django.db.models.deletion
import knowledge_base.rag.vector_field
from django.conf import settings
from django.db import migrations, models


VECTOR_HNSW_INDEX = "knowledge_base_rag_embedding_hnsw_cosine"


def _embedding_dimensions() -> int:
    return int(getattr(settings, "LIVIA_RAG_EMBEDDING_DIMENSION", 1536) or 1536)


def forwards_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    dimensions = _embedding_dimensions()
    table = "knowledge_base_tenantragchunkembedding"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector")
        cursor.execute(
            f"""
            ALTER TABLE {table}
            ALTER COLUMN vector TYPE vector({dimensions})
            USING (
                CASE
                    WHEN vector IS NULL THEN NULL
                    WHEN jsonb_typeof(vector) = 'array'
                         AND jsonb_array_length(vector) = {dimensions}
                    THEN (vector::text)::vector
                    ELSE NULL
                END
            )
            """
        )
        cursor.execute(
            f"""
            CREATE INDEX IF NOT EXISTS {VECTOR_HNSW_INDEX}
            ON {table}
            USING hnsw (vector vector_cosine_ops)
            """
        )


def backwards_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    table = "knowledge_base_tenantragchunkembedding"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP INDEX IF EXISTS {VECTOR_HNSW_INDEX}")
        cursor.execute(
            f"""
            ALTER TABLE {table}
            ALTER COLUMN vector TYPE jsonb
            USING to_jsonb(vector::float4[])
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0007_tenantragconfiguration_retrieval_enabled"),
        ("tenants", "0006_tenantallowedorigin"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagRetrievalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conversation_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("empty", "Empty"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("backend", models.CharField(blank=True, max_length=40)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("max_score", models.FloatField(default=0.0)),
                ("threshold", models.FloatField(default=0.0)),
                ("hit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="tenantragchunkembedding",
                    name="vector",
                    field=knowledge_base.rag.vector_field.RagVectorField(
                        blank=True,
                        default=list,
                        dimensions=1536,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards_pgvector, backwards_pgvector),
            ],
        ),
        migrations.AddIndex(
            model_name="tenantragchunkembedding",
            index=models.Index(
                fields=["tenant", "provider", "model", "dimension", "is_active"],
                name="knowledge_b_tenant__1db524_idx",
            ),
        ),
        migrations.AddField(
            model_name="ragretrievalevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_retrieval_events",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="ragretrievalevent",
            index=models.Index(fields=["tenant", "created_at"], name="knowledge_b_tenant__4113d3_idx"),
        ),
        migrations.AddIndex(
            model_name="ragretrievalevent",
            index=models.Index(fields=["tenant", "status", "created_at"], name="knowledge_b_tenant__e7d9ae_idx"),
        ),
        migrations.AddIndex(
            model_name="ragretrievalevent",
            index=models.Index(fields=["tenant", "hit", "created_at"], name="knowledge_b_tenant__5cd7a4_idx"),
        ),
    ]
