# Generated by Django 6.0.6 on 2026-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0008_rag_pgvector_and_retrieval_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragretrievalevent',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ragretrievalevent',
            name='threshold_source',
            field=models.CharField(blank=True, default='global_default', max_length=30),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='min_similarity_score',
            field=models.FloatField(blank=True, help_text='Override por tenant para threshold de similaridade (0.0 a 1.0).', null=True),
        ),
    ]
