# Generated by Django 6.0.6 on 2026-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0009_ragretrievalevent_dry_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='max_context_chars',
            field=models.PositiveIntegerField(blank=True, help_text='Orçamento máximo de caracteres de contexto RAG no chat (null = default global).', null=True),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='max_retrieved_chunks',
            field=models.PositiveIntegerField(blank=True, help_text='Limite máximo de chunks recuperados no chat (null = default global).', null=True),
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='retrieval_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Timeout da recuperação/embed da query no chat (null = default global).', null=True),
        ),
    ]
