# Generated by Django 6.0.6 on 2026-08-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0010_tenantragconfiguration_chat_retrieval_limits'),
        ('tenants', '0007_assistantprofile_business_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRagOperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('inventory', 'Inventário da origem'), ('sync_export', 'Sincronização de documentos'), ('build_chunks', 'Atualização de chunks'), ('index_embeddings', 'Geração de embeddings pendentes'), ('full_reindex', 'Reindexação completa')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('run_id', models.CharField(max_length=64)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_requests', to='knowledge_base.tenantragindexrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_operation_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_operation_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='knowledge_b_tenant__c7686f_idx'), models.Index(fields=['tenant', 'operation', 'created_at'], name='knowledge_b_tenant__927c1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'run_id'), name='unique_rag_operation_run_per_tenant')],
            },
        ),
    ]
