# Generated by Django 6.0.6 on 2026-08-01 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0011_tenantragoperationrequest'),
        ('tenants', '0007_assistantprofile_business_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantragoperationrequest',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantragoperationrequest',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tenantragoperationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('tenant',), name='unique_active_rag_operation_per_tenant'),
        ),
    ]
