# Generated by Django 6.0.6 on 2026-08-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0012_tenantragoperationrequest_attempt_count_and_more'),
        ('tenants', '0007_assistantprofile_business_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('configuration', 'Configuration'), ('environment', 'Environment'), ('database', 'Database'), ('vector_health', 'Vector health'), ('rag_operations', 'RAG operations'), ('retrieval', 'Retrieval'), ('grounded_ai', 'Grounded AI'), ('openai_provider', 'OpenAI provider'), ('token_usage', 'Token usage'), ('tenant_isolation', 'Tenant isolation'), ('integration_safety', 'Integration safety')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('rule_id', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('detected_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(default='operational_alert_sync', max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('resolution_source', models.CharField(blank=True, choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alerts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='knowledge_b_tenant__1d50d3_idx'), models.Index(fields=['tenant', 'severity'], name='knowledge_b_tenant__68b728_idx'), models.Index(fields=['tenant', 'category'], name='knowledge_b_tenant__43d15d_idx'), models.Index(fields=['tenant', 'last_seen_at'], name='knowledge_b_tenant__e4dbb4_idx'), models.Index(fields=['tenant', 'fingerprint'], name='knowledge_b_tenant__637134_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'fingerprint'), name='unique_operational_alert_fingerprint_per_tenant')],
            },
        ),
    ]
