# Generated by Django 6.0.6 on 2026-08-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0013_operational_alerts'),
        ('tenants', '0007_assistantprofile_business_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalMonitoringBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('portal', 'Portal'), ('cli', 'CLI'), ('scheduler', 'Scheduler'), ('test', 'Test')], default='cli', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('period', models.CharField(default='7d', max_length=10)),
                ('worker_identifier', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('tenants_total', models.PositiveIntegerField(default=0)),
                ('tenants_processed', models.PositiveIntegerField(default=0)),
                ('tenants_failed', models.PositiveIntegerField(default=0)),
                ('tenants_skipped', models.PositiveIntegerField(default=0)),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('alerts_updated', models.PositiveIntegerField(default=0)),
                ('alerts_resolved', models.PositiveIntegerField(default=0)),
                ('alerts_reopened', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_category', models.CharField(blank=True, max_length=40)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantOperationalMonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('alerts_updated', models.PositiveIntegerField(default=0)),
                ('alerts_resolved', models.PositiveIntegerField(default=0)),
                ('alerts_reopened', models.PositiveIntegerField(default=0)),
                ('alerts_active', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_category', models.CharField(blank=True, max_length=40)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='tenantragconfiguration',
            name='operational_monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Habilita monitoramento automático de alertas operacionais para este tenant.'),
        ),
        migrations.AddIndex(
            model_name='tenantragconfiguration',
            index=models.Index(fields=['operational_monitoring_enabled'], name='knowledge_b_operati_22d732_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalmonitoringbatchrun',
            index=models.Index(fields=['status', 'started_at'], name='knowledge_b_status_134f06_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalmonitoringbatchrun',
            index=models.Index(fields=['trigger', 'started_at'], name='knowledge_b_trigger_094ccd_idx'),
        ),
        migrations.AddField(
            model_name='tenantoperationalmonitoringrun',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_runs', to='knowledge_base.operationalmonitoringbatchrun'),
        ),
        migrations.AddField(
            model_name='tenantoperationalmonitoringrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_monitoring_runs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalmonitoringrun',
            index=models.Index(fields=['tenant', 'status', 'started_at'], name='knowledge_b_tenant__5503ea_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalmonitoringrun',
            index=models.Index(fields=['batch', 'tenant'], name='knowledge_b_batch_i_3a6a88_idx'),
        ),
    ]
