# Generated by Django 6.0.6 on 2026-08-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0014_operational_monitoring'),
        ('tenants', '0007_assistantprofile_business_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOperationalAlertSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantOperationalMaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All operational rules'), ('categories', 'Specific categories'), ('rules', 'Specific rule ids'), ('resource', 'Specific resource reference')], default='all', max_length=20)),
                ('scope_categories', models.JSONField(blank=True, default=list)),
                ('scope_rule_ids', models.JSONField(blank=True, default=list)),
                ('scope_resource_reference', models.CharField(blank=True, max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_note', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='ack_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operational_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operational_alerts', to='tenants.tenantmembership'),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='last_sync_batch_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalert',
            index=models.Index(fields=['tenant', 'assigned_to'], name='knowledge_b_tenant__8cd46a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalert',
            index=models.Index(fields=['tenant', 'ack_due_at'], name='knowledge_b_tenant__2c63df_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalert',
            index=models.Index(fields=['tenant', 'resolution_due_at'], name='knowledge_b_tenant__a8c722_idx'),
        ),
        migrations.AddField(
            model_name='tenantoperationalalertsilence',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='knowledge_base.tenantoperationalalert'),
        ),
        migrations.AddField(
            model_name='tenantoperationalalertsilence',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_operational_alert_silences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoperationalalertsilence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operational_alert_silences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoperationalalertsilence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alert_silences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantoperationalmaintenancewindow',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_operational_maintenance_windows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoperationalmaintenancewindow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operational_maintenance_windows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantoperationalmaintenancewindow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_maintenance_windows', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalertsilence',
            index=models.Index(fields=['tenant', 'alert', 'ends_at'], name='knowledge_b_tenant__c46152_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalertsilence',
            index=models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='knowledge_b_tenant__726680_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalmaintenancewindow',
            index=models.Index(fields=['tenant', 'status', 'starts_at'], name='knowledge_b_tenant__d86baf_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalmaintenancewindow',
            index=models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='knowledge_b_tenant__7b35e4_idx'),
        ),
    ]
