# Generated by Django 6.0.6 on 2026-08-01 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0015_operational_governance'),
        ('tenants', '0007_assistantprofile_business_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='escalation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='escalation_trigger',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='last_reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantoperationalalert',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='tenantoperationalalert',
            index=models.Index(fields=['tenant', 'escalation_level'], name='knowledge_b_tenant__ae8060_idx'),
        ),
    ]
