# Generated by Django 6.0.6 on 2026-08-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0016_operational_work_queue"),
        ("tenants", "0007_assistantprofile_business_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantOperationalNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("notify_on_assignment", models.BooleanField(default=True)),
                ("notify_on_escalation", models.BooleanField(default=True)),
                ("notify_on_sla_breach", models.BooleanField(default=True)),
                ("notify_on_resolution", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[("immediate", "Immediate"), ("daily", "Daily"), ("weekly", "Weekly")],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="America/Sao_Paulo", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notification_preference",
                        to="tenants.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notification_preferences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "membership"),
                        name="unique_operational_notification_pref_per_membership",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantOperationalNotificationWorkerRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("worker_identifier", models.CharField(blank=True, max_length=120)),
                ("dry_run", models.BooleanField(default=False)),
                ("channel_filter", models.CharField(blank=True, max_length=20)),
                ("tenant_slug", models.CharField(blank=True, max_length=120)),
                ("claimed", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("cancelled", models.PositiveIntegerField(default=0)),
                ("retry_scheduled", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [models.Index(fields=["status", "started_at"], name="knowledge_b_status_264cda_idx")],
            },
        ),
        migrations.CreateModel(
            name="TenantOperationalNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("email", "Email"), ("webhook", "Webhook")],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("sla", "SLA"),
                            ("escalation", "Escalation"),
                            ("ownership", "Ownership"),
                            ("maintenance", "Maintenance"),
                            ("monitoring", "Monitoring"),
                            ("digest", "Digest"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("operational_alert", "Operational alert"),
                            ("maintenance_window", "Maintenance window"),
                            ("monitoring_run", "Monitoring run"),
                            ("digest", "Digest"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                (
                    "destination_route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alert_detail", "Alert detail"),
                            ("work_queue", "Work queue"),
                            ("my_work", "My work"),
                            ("maintenance", "Maintenance"),
                            ("health", "Health"),
                            ("notifications", "Notifications"),
                        ],
                        max_length=40,
                    ),
                ),
                ("destination_object_id", models.CharField(blank=True, max_length=40)),
                ("deduplication_key", models.CharField(max_length=220)),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_category", models.CharField(blank=True, max_length=40)),
                ("last_error_summary", models.CharField(blank=True, max_length=500)),
                ("processing_token", models.CharField(blank=True, max_length=120)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notifications",
                        to="tenants.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notifications",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["tenant", "recipient_membership", "read_at"], name="knowledge_b_tenant__91f759_idx"),
                    models.Index(fields=["tenant", "recipient_membership", "status"], name="knowledge_b_tenant__740f48_idx"),
                    models.Index(fields=["status", "scheduled_at"], name="knowledge_b_status_574051_idx"),
                    models.Index(fields=["channel", "status"], name="knowledge_b_channel_7abdec_idx"),
                    models.Index(fields=["next_attempt_at"], name="knowledge_b_next_at_3ced81_idx"),
                    models.Index(fields=["tenant", "status", "created_at"], name="knowledge_b_tenant__672704_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deduplication_key",),
                        name="unique_operational_notification_dedupe_key",
                    )
                ],
            },
        ),
    ]
