# Generated by Django 6.0.6 on 2026-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0017_operational_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexed_content_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='last_index_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='lifecycle_status',
            field=models.CharField(choices=[('new', 'New'), ('imported', 'Imported'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('stale', 'Stale'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='new', max_length=20),
        ),
    ]
