# Generated by Django 6.0.6 on 2026-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0019_tenantragconfiguration_source_mode'),
        ('tenants', '0008_assistantprofile_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragretrievalevent',
            name='retrieval_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantragdocumentchunk',
            name='chunk_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantragdrivefilemanifest',
            name='document_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='tenantragdrivefilemanifest',
            index=models.Index(fields=['tenant', 'updated_at'], name='knowledge_b_tenant__46377a_idx'),
        ),
    ]
