from django.urls import path

from . import (
    analytics_views,
    integration_views,
    knowledge_base_views,
    notification_views,
    quality_views,
    views,
    work_queue_views,
)

app_name = "operations_portal"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("qualidade/", quality_views.quality_dashboard, name="quality_dashboard"),
    path("qualidade/tenants/<slug:slug>/", quality_views.quality_tenant_detail, name="quality_tenant_detail"),
    path("qualidade/lacunas/", quality_views.quality_knowledge_gaps, name="quality_knowledge_gaps"),
    path("qualidade/conversas/", quality_views.quality_conversations, name="quality_conversations"),
    path("qualidade/conversas/<int:pk>/", quality_views.quality_conversation_transcript, name="quality_conversation_transcript"),
    path("qualidade/documentos/", quality_views.quality_documents, name="quality_documents"),
    path("qualidade/outbox/", quality_views.quality_outbox, name="quality_outbox"),
    path("conversas/", views.conversation_list, name="conversation_list"),
    path("conversas/<int:pk>/", views.conversation_detail, name="conversation_detail"),
    path("leads/", views.lead_list, name="lead_list"),
    path("handoffs/", views.handoff_list, name="handoff_list"),
    path("handoffs/<int:pk>/", views.handoff_detail, name="handoff_detail"),
    path("handoffs/<int:pk>/status/", views.update_handoff_status, name="handoff_update_status"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/novo/", views.tenant_create, name="tenant_create"),
    path("tenants/<int:pk>/", views.tenant_detail, name="tenant_detail"),
    path("configuracoes/", views.settings_view, name="settings"),
    path("integracoes/", integration_views.integrations_dashboard, name="integrations"),
    path("integracoes/outbox/<int:pk>/", integration_views.outbox_event_detail, name="outbox_event_detail"),
    path("integracoes/outbox/<int:pk>/reenfileirar/", integration_views.outbox_event_requeue, name="outbox_event_requeue"),
    path("leads/<int:pk>/", views.lead_detail, name="lead_detail"),
    path("leads/<int:pk>/reprocessar-crm/", views.retry_lead_crm_dispatch, name="lead_retry_crm"),
    path("base-de-conhecimento/", knowledge_base_views.knowledge_base_dashboard, name="knowledge_base_dashboard"),
    path("base-de-conhecimento/documentos/", knowledge_base_views.knowledge_base_documents, name="knowledge_base_documents"),
    path("base-de-conhecimento/documentos/novo/", knowledge_base_views.knowledge_base_document_create, name="knowledge_base_document_create"),
    path("base-de-conhecimento/documentos/importar/", knowledge_base_views.knowledge_base_document_import, name="knowledge_base_document_import"),
    path("base-de-conhecimento/documentos/<int:pk>/", knowledge_base_views.knowledge_base_document_detail, name="knowledge_base_document_detail"),
    path("base-de-conhecimento/documentos/<int:pk>/editar/", knowledge_base_views.knowledge_base_document_edit, name="knowledge_base_document_edit"),
    path("base-de-conhecimento/chunks/", knowledge_base_views.knowledge_base_chunks, name="knowledge_base_chunks"),
    path("base-de-conhecimento/configuracao/", knowledge_base_views.knowledge_base_config, name="knowledge_base_config"),
    path("base-de-conhecimento/busca/", knowledge_base_views.knowledge_base_diagnostic, name="knowledge_base_diagnostic"),
    path("base-de-conhecimento/eventos/", knowledge_base_views.knowledge_base_events, name="knowledge_base_events"),
    path("base-de-conhecimento/atualizacao/", knowledge_base_views.knowledge_base_operations, name="knowledge_base_operations"),
    path("base-de-conhecimento/atualizacao/solicitar/", knowledge_base_views.knowledge_base_operation_submit, name="knowledge_base_operation_submit"),
    path("base-de-conhecimento/atualizacao/<int:pk>/", knowledge_base_views.knowledge_base_operation_detail, name="knowledge_base_operation_detail"),
    path("base-de-conhecimento/saude/", knowledge_base_views.knowledge_base_health, name="knowledge_base_health"),
    path("base-de-conhecimento/saude/sincronizar/", knowledge_base_views.knowledge_base_health_sync, name="knowledge_base_health_sync"),
    path("base-de-conhecimento/alertas/", knowledge_base_views.knowledge_base_alerts, name="knowledge_base_alerts"),
    path("base-de-conhecimento/alertas/<int:pk>/", knowledge_base_views.knowledge_base_alert_detail, name="knowledge_base_alert_detail"),
    path("operacoes/minhas-pendencias/", work_queue_views.operational_my_work, name="operational_my_work"),
    path("operacoes/fila/", work_queue_views.operational_work_queue, name="operational_work_queue"),
    path("operacoes/analytics/", analytics_views.operational_analytics, name="operational_analytics"),
    path("operacoes/analytics/exportar/", analytics_views.operational_analytics_export, name="operational_analytics_export"),
    path("notificacoes/", notification_views.operational_notifications, name="operational_notifications"),
    path("notificacoes/preferencias/", notification_views.operational_notification_preferences, name="operational_notification_preferences"),
    path("notificacoes/<int:pk>/marcar-lida/", notification_views.operational_notification_mark_read, name="operational_notification_mark_read"),
    path("notificacoes/marcar-todas-lidas/", notification_views.operational_notification_mark_all_read, name="operational_notification_mark_all_read"),
    path("base-de-conhecimento/alertas/<int:pk>/assumir/", work_queue_views.operational_alert_claim, name="operational_alert_claim"),
    path("base-de-conhecimento/alertas/<int:pk>/reconhecer/", knowledge_base_views.knowledge_base_alert_acknowledge, name="knowledge_base_alert_acknowledge"),
    path("base-de-conhecimento/alertas/<int:pk>/transferir/", work_queue_views.operational_alert_transfer, name="operational_alert_transfer"),
    path("base-de-conhecimento/alertas/<int:pk>/escalar/", work_queue_views.operational_alert_escalate, name="operational_alert_escalate"),
    path("base-de-conhecimento/alertas/<int:pk>/encerrar-escalonamento/", work_queue_views.operational_alert_deescalate, name="operational_alert_deescalate"),
    path("base-de-conhecimento/alertas/<int:pk>/resolver/", knowledge_base_views.knowledge_base_alert_resolve, name="knowledge_base_alert_resolve"),
    path("base-de-conhecimento/alertas/<int:pk>/atribuir/", knowledge_base_views.knowledge_base_alert_assign, name="knowledge_base_alert_assign"),
    path("base-de-conhecimento/alertas/<int:pk>/desatribuir/", work_queue_views.operational_alert_unassign, name="knowledge_base_alert_unassign"),
    path("base-de-conhecimento/alertas/<int:pk>/silenciar/", knowledge_base_views.knowledge_base_alert_silence, name="knowledge_base_alert_silence"),
    path("base-de-conhecimento/alertas/<int:pk>/dessilenciar/", knowledge_base_views.knowledge_base_alert_unsilence, name="knowledge_base_alert_unsilence"),
    path("base-de-conhecimento/manutencoes/", knowledge_base_views.knowledge_base_maintenance, name="knowledge_base_maintenance"),
    path("base-de-conhecimento/manutencoes/nova/", knowledge_base_views.knowledge_base_maintenance_create, name="knowledge_base_maintenance_create"),
    path("base-de-conhecimento/manutencoes/<int:pk>/cancelar/", knowledge_base_views.knowledge_base_maintenance_cancel, name="knowledge_base_maintenance_cancel"),
    path("<slug:section>/", views.placeholder, name="placeholder"),
]
