# Generated by Django 6.0.6 on 2026-07-18 14:26

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_assistantprofile_widget_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='handoff_whatsapp_label',
            field=models.CharField(default='Falar com um especialista', max_length=80),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='handoff_whatsapp_message',
            field=models.CharField(blank=True, default='Olá, vim pelo atendimento da Lívia e gostaria de continuar com um especialista.', max_length=240),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='handoff_whatsapp_number',
            field=models.CharField(blank=True, max_length=20, validators=[tenants.models.validate_whatsapp_number]),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='human_handoff_channel',
            field=models.CharField(choices=[('disabled', 'Desativado'), ('whatsapp', 'WhatsApp')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='human_handoff_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
