# Generated by Django 6.0.6 on 2026-07-19 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_assistantprofile_handoff_whatsapp_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant__name', 'user__username'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenants_ten_tenant__b981b3_idx'), models.Index(fields=['user', 'is_active'], name='tenants_ten_user_id_8b073c_idx'), models.Index(fields=['tenant', 'role'], name='tenants_ten_tenant__1c6fa4_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_membership_per_user')],
            },
        ),
    ]
