# Generated by Django 6.0.6 on 2026-07-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenant_allowed_origins', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_origins', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'origin'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenants_ten_tenant__c0d085_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'origin'), name='unique_tenant_allowed_origin')],
            },
        ),
    ]
