# Generated by Django 6.0.6 on 2026-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_assistantprofile_business_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='notification_email',
            field=models.EmailField(blank=True, default='', help_text='Destinatário comercial de leads/notificações deste tenant. Vazio usa o fallback global.', max_length=254),
        ),
    ]
