"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def _cast_env_value(value, cast):
    if cast is bool:
        return str(value).strip().lower() in {"1", "true", "yes", "on"}
    if cast is str:
        return str(value)
    return cast(value)


def env_first(*names: str, default="", cast=str):
    for name in names:
        value = config(name, default="", cast=str)
        if str(value).strip() != "":
            return _cast_env_value(value, cast)
    return default


def csv_env(*names: str, default: str = "") -> list[str]:
    raw_value = env_first(*names, default=default, cast=str)
    return [item.strip() for item in str(raw_value or "").split(",") if item.strip()]


SECRET_KEY = env_first(
    "DJANGO_SECRET_KEY",
    "SECRET_KEY",
    default="django-insecure-local-dev-only-change-me",
    cast=str,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_first("DJANGO_DEBUG", "DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = csv_env("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS", default="127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = csv_env("DJANGO_CSRF_TRUSTED_ORIGINS", "CSRF_TRUSTED_ORIGINS", default="")


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Lívia Platform
    "tenants",
    "assistant_core",
    "conversations",
    "leads",
    "knowledge_base",
    "widget",
    "integrations",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'config.middleware.LiviaWidgetCorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production security
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = config(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=not DEBUG,
    cast=bool,
)
SESSION_COOKIE_SECURE = config(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)
CSRF_COOKIE_SECURE = config(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)

# Começa curto e pode ser ampliado após validação em produção.
SECURE_HSTS_SECONDS = config(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=300 if not DEBUG else 0,
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=False,
    cast=bool,
)



SMART360_BASE_URL = config("SMART360_BASE_URL", default="")
SMART360_M2M_TOKEN = config("SMART360_M2M_TOKEN", default="")
SMART360_LEAD_DISPATCH_ENABLED = config("SMART360_LEAD_DISPATCH_ENABLED", default=False, cast=bool)
SMART360_LEAD_DISPATCH_DRY_RUN = config("SMART360_LEAD_DISPATCH_DRY_RUN", default=True, cast=bool)

LIVIA_HANDOFF_NOTIFICATIONS_ENABLED = config("LIVIA_HANDOFF_NOTIFICATIONS_ENABLED", default=False, cast=bool)
LIVIA_HANDOFF_NOTIFICATIONS_DRY_RUN = config("LIVIA_HANDOFF_NOTIFICATIONS_DRY_RUN", default=True, cast=bool)
LIVIA_HANDOFF_NOTIFICATION_EMAIL = config("LIVIA_HANDOFF_NOTIFICATION_EMAIL", default="contato@smartcontrolbrasil.com.br")

LIVIA_AI_ENABLED = config("LIVIA_AI_ENABLED", default=False, cast=bool)
LIVIA_AI_DRY_RUN = config("LIVIA_AI_DRY_RUN", default=True, cast=bool)
LIVIA_OPENAI_API_KEY = config("LIVIA_OPENAI_API_KEY", default="")
LIVIA_OPENAI_MODEL = config("LIVIA_OPENAI_MODEL", default="gpt-4.1-mini")
LIVIA_OPENAI_TIMEOUT_SECONDS = config("LIVIA_OPENAI_TIMEOUT_SECONDS", default=8, cast=int)
LIVIA_OPENAI_MAX_OUTPUT_TOKENS = config("LIVIA_OPENAI_MAX_OUTPUT_TOKENS", default=350, cast=int)
LIVIA_OPENAI_TEMPERATURE = config("LIVIA_OPENAI_TEMPERATURE", default=0.3, cast=float)


LIVIA_ALLOWED_WIDGET_ORIGINS = csv_env("LIVIA_ALLOWED_WIDGET_ORIGINS", default="")

LIVIA_MAX_MESSAGE_LENGTH = config("LIVIA_MAX_MESSAGE_LENGTH", default=1200, cast=int)
LIVIA_CHAT_RATE_LIMIT_ENABLED = config("LIVIA_CHAT_RATE_LIMIT_ENABLED", default=True, cast=bool)
LIVIA_CHAT_RATE_LIMIT_REQUESTS = config("LIVIA_CHAT_RATE_LIMIT_REQUESTS", default=20, cast=int)
LIVIA_CHAT_RATE_LIMIT_WINDOW_SECONDS = config("LIVIA_CHAT_RATE_LIMIT_WINDOW_SECONDS", default=300, cast=int)
LIVIA_SPAM_GUARD_ENABLED = config("LIVIA_SPAM_GUARD_ENABLED", default=True, cast=bool)

LIVIA_WEBHOOKS_ENABLED = config("LIVIA_WEBHOOKS_ENABLED", default=False, cast=bool)
LIVIA_WEBHOOKS_DRY_RUN = config("LIVIA_WEBHOOKS_DRY_RUN", default=True, cast=bool)
LIVIA_WEBHOOK_TIMEOUT_SECONDS = config("LIVIA_WEBHOOK_TIMEOUT_SECONDS", default=6, cast=int)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "assistant_core": {"handlers": ["console"], "level": "INFO"},
        "leads": {"handlers": ["console"], "level": "INFO"},
        "integrations": {"handlers": ["console"], "level": "INFO"},
    },
}
