"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

from decouple import config

from config.database import build_database_config, is_running_tests, parse_database_conn_max_age

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def _cast_env_value(value, cast):
    if cast is bool:
        return str(value).strip().lower() in {"1", "true", "yes", "on"}
    if cast is str:
        return str(value)
    return cast(value)


def env_first(*names: str, default="", cast=str):
    for name in names:
        value = config(name, default="", cast=str)
        if str(value).strip() != "":
            return _cast_env_value(value, cast)
    return default


def csv_env(*names: str, default: str = "") -> list[str]:
    raw_value = env_first(*names, default=default, cast=str)
    return [item.strip() for item in str(raw_value or "").split(",") if item.strip()]


SECRET_KEY = env_first(
    "DJANGO_SECRET_KEY",
    "SECRET_KEY",
    default="django-insecure-local-dev-only-change-me",
    cast=str,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_first("DJANGO_DEBUG", "DEBUG", default=True, cast=bool)
RUNNING_TESTS = is_running_tests(sys.argv, config("DJANGO_RUNNING_TESTS", default=""))

ALLOWED_HOSTS = csv_env("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS", default="127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = csv_env("DJANGO_CSRF_TRUSTED_ORIGINS", "CSRF_TRUSTED_ORIGINS", default="")


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Lívia Platform
    "tenants",
    "assistant_core",
    "conversations",
    "leads",
    "knowledge_base",
    "widget",
    "integrations",
    "operations_portal",
    "audit",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'config.middleware.LiviaWidgetCorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_CONN_MAX_AGE = parse_database_conn_max_age(config("DATABASE_CONN_MAX_AGE", default="60"))
DATABASES = build_database_config(
    debug=DEBUG,
    base_dir=BASE_DIR,
    database_url=config("DATABASE_URL", default=""),
    conn_max_age=DATABASE_CONN_MAX_AGE,
    running_tests=RUNNING_TESTS,
    allow_external_test_database_url=config("DJANGO_ALLOW_EXTERNAL_TEST_DATABASE_URL", default=False, cast=bool),
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production security
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = False if RUNNING_TESTS else config(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=not DEBUG,
    cast=bool,
)
SESSION_COOKIE_SECURE = config(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)
CSRF_COOKIE_SECURE = config(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)

# Começa curto e pode ser ampliado após validação em produção.
SECURE_HSTS_SECONDS = config(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=300 if not DEBUG else 0,
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=False,
    cast=bool,
)



SMART360_BASE_URL = config("SMART360_BASE_URL", default="")
SMART360_M2M_TOKEN = config("SMART360_M2M_TOKEN", default="")
SMART360_LEAD_DISPATCH_ENABLED = config("SMART360_LEAD_DISPATCH_ENABLED", default=False, cast=bool)
SMART360_LEAD_DISPATCH_DRY_RUN = config("SMART360_LEAD_DISPATCH_DRY_RUN", default=True, cast=bool)

LIVIA_HANDOFF_NOTIFICATIONS_ENABLED = config("LIVIA_HANDOFF_NOTIFICATIONS_ENABLED", default=False, cast=bool)
LIVIA_HANDOFF_NOTIFICATIONS_DRY_RUN = config("LIVIA_HANDOFF_NOTIFICATIONS_DRY_RUN", default=True, cast=bool)
LIVIA_HANDOFF_NOTIFICATION_EMAIL = config("LIVIA_HANDOFF_NOTIFICATION_EMAIL", default="contato@smartcontrolbrasil.com.br")

LIVIA_AI_ENABLED = config("LIVIA_AI_ENABLED", default=False, cast=bool)
LIVIA_AI_DRY_RUN = config("LIVIA_AI_DRY_RUN", default=True, cast=bool)
LIVIA_AI_GROUNDED_SYNTHESIS_ENABLED = config("LIVIA_AI_GROUNDED_SYNTHESIS_ENABLED", default=False, cast=bool)
LIVIA_AI_GROUNDED_SYNTHESIS_TENANT_ALLOWLIST = config("LIVIA_AI_GROUNDED_SYNTHESIS_TENANT_ALLOWLIST", default="")
LIVIA_OPENAI_API_KEY = config("LIVIA_OPENAI_API_KEY", default="")
LIVIA_GOOGLE_SERVICE_ACCOUNT_FILE = config(
    "LIVIA_GOOGLE_SERVICE_ACCOUNT_FILE",
    default="",
)
LIVIA_OPENAI_MODEL = config("LIVIA_OPENAI_MODEL", default="gpt-4.1-mini")
LIVIA_OPENAI_TIMEOUT_SECONDS = config("LIVIA_OPENAI_TIMEOUT_SECONDS", default=8, cast=int)
LIVIA_OPENAI_MAX_OUTPUT_TOKENS = config("LIVIA_OPENAI_MAX_OUTPUT_TOKENS", default=350, cast=int)
LIVIA_OPENAI_TEMPERATURE = config("LIVIA_OPENAI_TEMPERATURE", default=0.3, cast=float)
LIVIA_RAG_EXPORT_MAX_BYTES = config("LIVIA_RAG_EXPORT_MAX_BYTES", default=1000000, cast=int)
LIVIA_RAG_SYNC_RUNNING_TIMEOUT_SECONDS = config("LIVIA_RAG_SYNC_RUNNING_TIMEOUT_SECONDS", default=1800, cast=int)
LIVIA_RAG_CHUNK_SIZE_CHARS = config("LIVIA_RAG_CHUNK_SIZE_CHARS", default=1200, cast=int)
LIVIA_RAG_CHUNK_OVERLAP_CHARS = config("LIVIA_RAG_CHUNK_OVERLAP_CHARS", default=120, cast=int)
LIVIA_RAG_MAX_CHUNKS_PER_DOCUMENT = config("LIVIA_RAG_MAX_CHUNKS_PER_DOCUMENT", default=400, cast=int)
LIVIA_RAG_INDEXING_ENABLED = config("LIVIA_RAG_INDEXING_ENABLED", default=False, cast=bool)
LIVIA_RAG_OPERATIONS_ENABLED = config("LIVIA_RAG_OPERATIONS_ENABLED", default=False, cast=bool)
LIVIA_RAG_OPERATIONS_DRY_RUN = config("LIVIA_RAG_OPERATIONS_DRY_RUN", default=True, cast=bool)
LIVIA_RAG_OPERATIONS_LEASE_SECONDS = config("LIVIA_RAG_OPERATIONS_LEASE_SECONDS", default=3600, cast=int)
LIVIA_RAG_ENABLED = config("LIVIA_RAG_ENABLED", default=False, cast=bool)
LIVIA_RAG_DRY_RUN = config("LIVIA_RAG_DRY_RUN", default=True, cast=bool)
LIVIA_RAG_ACTIVE_TENANT_ALLOWLIST = config("LIVIA_RAG_ACTIVE_TENANT_ALLOWLIST", default="")
LIVIA_RAG_MIN_SIMILARITY_SCORE = config("LIVIA_RAG_MIN_SIMILARITY_SCORE", default=0.25, cast=float)
LIVIA_RAG_MAX_RETRIEVED_CHUNKS = config("LIVIA_RAG_MAX_RETRIEVED_CHUNKS", default=5, cast=int)
LIVIA_RAG_MAX_CONTEXT_CHARS = config("LIVIA_RAG_MAX_CONTEXT_CHARS", default=3000, cast=int)
LIVIA_RAG_MAX_CHUNKS_PER_MANIFEST = config("LIVIA_RAG_MAX_CHUNKS_PER_MANIFEST", default=2, cast=int)
LIVIA_RAG_VECTOR_CANDIDATE_LIMIT = config("LIVIA_RAG_VECTOR_CANDIDATE_LIMIT", default=20, cast=int)
LIVIA_RAG_VECTOR_BACKEND = config("LIVIA_RAG_VECTOR_BACKEND", default="auto")
LIVIA_ENVIRONMENT = config("LIVIA_ENVIRONMENT", default="development")
LIVIA_ALLOW_FAKE_EMBEDDINGS = config("LIVIA_ALLOW_FAKE_EMBEDDINGS", default=False, cast=bool)
LIVIA_RAG_EMBEDDING_PROVIDER = config("LIVIA_RAG_EMBEDDING_PROVIDER", default="openai")
LIVIA_RAG_EMBEDDING_API_KEY = config("LIVIA_RAG_EMBEDDING_API_KEY", default="")
LIVIA_RAG_EMBEDDING_MODEL = config("LIVIA_RAG_EMBEDDING_MODEL", default="text-embedding-3-small")
LIVIA_RAG_EMBEDDING_DIMENSION = config("LIVIA_RAG_EMBEDDING_DIMENSION", default=1536, cast=int)
# Alias documentado para a mesma configuração centralizada de dimensão.
LIVIA_RAG_EMBEDDING_DIMENSIONS = LIVIA_RAG_EMBEDDING_DIMENSION
LIVIA_RAG_EMBEDDING_BATCH_SIZE = config("LIVIA_RAG_EMBEDDING_BATCH_SIZE", default=32, cast=int)
LIVIA_RAG_EMBEDDING_TIMEOUT_SECONDS = config("LIVIA_RAG_EMBEDDING_TIMEOUT_SECONDS", default=30, cast=int)
LIVIA_RAG_EMBEDDING_MAX_RETRIES = config("LIVIA_RAG_EMBEDDING_MAX_RETRIES", default=3, cast=int)
LIVIA_RAG_EMBEDDING_RETRY_BACKOFF_SECONDS = config(
    "LIVIA_RAG_EMBEDDING_RETRY_BACKOFF_SECONDS",
    default=1.0,
    cast=float,
)
LIVIA_RAG_INDEX_RUNNING_TIMEOUT_SECONDS = config(
    "LIVIA_RAG_INDEX_RUNNING_TIMEOUT_SECONDS",
    default=1800,
    cast=int,
)
LIVIA_RAG_ADMIN_SEARCH_MAX_RESULTS = config("LIVIA_RAG_ADMIN_SEARCH_MAX_RESULTS", default=20, cast=int)


LIVIA_ALLOWED_WIDGET_ORIGINS = csv_env("LIVIA_ALLOWED_WIDGET_ORIGINS", default="")
LIVIA_DEV_ALLOWED_WIDGET_ORIGINS = csv_env(
    "LIVIA_DEV_ALLOWED_WIDGET_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000",
)
LIVIA_ALLOW_ORIGINLESS_PUBLIC_API = config("LIVIA_ALLOW_ORIGINLESS_PUBLIC_API", default=RUNNING_TESTS, cast=bool)

LIVIA_MAX_MESSAGE_LENGTH = config("LIVIA_MAX_MESSAGE_LENGTH", default=1200, cast=int)
LIVIA_CHAT_RATE_LIMIT_ENABLED = config("LIVIA_CHAT_RATE_LIMIT_ENABLED", default=True, cast=bool)
LIVIA_CHAT_RATE_LIMIT_REQUESTS = config("LIVIA_CHAT_RATE_LIMIT_REQUESTS", default=20, cast=int)
LIVIA_CHAT_RATE_LIMIT_WINDOW_SECONDS = config("LIVIA_CHAT_RATE_LIMIT_WINDOW_SECONDS", default=300, cast=int)
LIVIA_CHAT_PROCESSING_TIMEOUT_SECONDS = config("LIVIA_CHAT_PROCESSING_TIMEOUT_SECONDS", default=30, cast=int)
LIVIA_SPAM_GUARD_ENABLED = config("LIVIA_SPAM_GUARD_ENABLED", default=True, cast=bool)

LIVIA_WEBHOOKS_ENABLED = config("LIVIA_WEBHOOKS_ENABLED", default=False, cast=bool)
LIVIA_WEBHOOKS_DRY_RUN = config("LIVIA_WEBHOOKS_DRY_RUN", default=True, cast=bool)
LIVIA_WEBHOOK_TIMEOUT_SECONDS = config("LIVIA_WEBHOOK_TIMEOUT_SECONDS", default=6, cast=int)
LIVIA_OUTBOX_LOCK_TIMEOUT_SECONDS = config("LIVIA_OUTBOX_LOCK_TIMEOUT_SECONDS", default=60, cast=int)
LIVIA_OUTBOX_BATCH_SIZE = config("LIVIA_OUTBOX_BATCH_SIZE", default=20, cast=int)
LIVIA_OUTBOX_MAX_ATTEMPTS = config("LIVIA_OUTBOX_MAX_ATTEMPTS", default=3, cast=int)
LIVIA_OUTBOX_BASE_RETRY_SECONDS = config("LIVIA_OUTBOX_BASE_RETRY_SECONDS", default=30, cast=int)
LIVIA_OUTBOX_MAX_RETRY_SECONDS = config("LIVIA_OUTBOX_MAX_RETRY_SECONDS", default=3600, cast=int)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "assistant_core": {"handlers": ["console"], "level": "INFO"},
        "leads": {"handlers": ["console"], "level": "INFO"},
        "integrations": {"handlers": ["console"], "level": "INFO"},
    },
}
