# Generated by Django 6.0.6 on 2026-07-19 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_assistantprofile_handoff_whatsapp_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('handoff.status_changed', 'Handoff status changed'), ('lead.crm_dispatch_retried', 'Lead CRM dispatch retried'), ('assistant_profile.updated', 'Assistant profile updated'), ('tenant.created', 'Tenant created'), ('tenant.updated', 'Tenant updated'), ('knowledge_document.created', 'Knowledge document created'), ('knowledge_document.updated', 'Knowledge document updated'), ('webhook_config.created', 'Webhook config created'), ('webhook_config.updated', 'Webhook config updated')], max_length=80)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('object_repr', models.CharField(blank=True, max_length=220)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='audit_audit_tenant__290b62_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx')],
            },
        ),
    ]
