# Generated by Django 6.0.6 on 2026-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('handoff.status_changed', 'Handoff status changed'), ('lead.crm_dispatch_retried', 'Lead CRM dispatch retried'), ('assistant_profile.updated', 'Assistant profile updated'), ('tenant.created', 'Tenant created'), ('tenant.updated', 'Tenant updated'), ('knowledge_document.created', 'Knowledge document created'), ('knowledge_document.updated', 'Knowledge document updated'), ('webhook_config.created', 'Webhook config created'), ('webhook_config.updated', 'Webhook config updated'), ('tenant_membership.created', 'Tenant membership created'), ('tenant_membership.updated', 'Tenant membership updated'), ('tenant_membership.deactivated', 'Tenant membership deactivated')], max_length=80),
        ),
    ]
