# Generated by Django 6.0.6 on 2026-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('handoff.status_changed', 'Handoff status changed'), ('lead.crm_dispatch_retried', 'Lead CRM dispatch retried'), ('assistant_profile.updated', 'Assistant profile updated'), ('tenant.created', 'Tenant created'), ('tenant.updated', 'Tenant updated'), ('knowledge_document.created', 'Knowledge document created'), ('knowledge_document.updated', 'Knowledge document updated'), ('webhook_config.created', 'Webhook config created'), ('webhook_config.updated', 'Webhook config updated'), ('tenant_membership.created', 'Tenant membership created'), ('tenant_membership.updated', 'Tenant membership updated'), ('tenant_membership.deactivated', 'Tenant membership deactivated'), ('tenant_origin.created', 'Tenant origin created'), ('tenant_origin.updated', 'Tenant origin updated'), ('tenant_origin.deactivated', 'Tenant origin deactivated'), ('outbox.requeued', 'Outbox requeued'), ('outbox.dead_lettered', 'Outbox dead lettered')], max_length=80),
        ),
    ]
