# Generated by Django 6.0.6 on 2026-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('handoff.status_changed', 'Handoff status changed'), ('lead.crm_dispatch_retried', 'Lead CRM dispatch retried'), ('assistant_profile.updated', 'Assistant profile updated'), ('tenant.created', 'Tenant created'), ('tenant.updated', 'Tenant updated'), ('knowledge_document.created', 'Knowledge document created'), ('knowledge_document.updated', 'Knowledge document updated'), ('webhook_config.created', 'Webhook config created'), ('webhook_config.updated', 'Webhook config updated'), ('tenant_membership.created', 'Tenant membership created'), ('tenant_membership.updated', 'Tenant membership updated'), ('tenant_membership.deactivated', 'Tenant membership deactivated'), ('tenant_origin.created', 'Tenant origin created'), ('tenant_origin.updated', 'Tenant origin updated'), ('tenant_origin.deactivated', 'Tenant origin deactivated'), ('outbox.requeued', 'Outbox requeued'), ('outbox.dead_lettered', 'Outbox dead lettered'), ('tenant.rag_configured', 'Tenant RAG configured'), ('tenant.rag_index_started', 'Tenant RAG index started'), ('tenant.rag_index_completed', 'Tenant RAG index completed'), ('tenant.rag_index_failed', 'Tenant RAG index failed'), ('tenant.rag_diagnostic_search', 'Tenant RAG diagnostic search'), ('tenant.rag_operation_requested', 'Tenant RAG operation requested'), ('tenant.rag_operation_rejected', 'Tenant RAG operation rejected'), ('tenant.rag_operation_started', 'Tenant RAG operation started'), ('tenant.rag_operation_completed', 'Tenant RAG operation completed'), ('tenant.rag_operation_failed', 'Tenant RAG operation failed'), ('tenant.rag_operation_duplicate', 'Tenant RAG operation duplicate'), ('tenant.rag_operation_stale_recovered', 'Tenant RAG operation stale recovered'), ('operational_alert.created', 'Operational alert created'), ('operational_alert.updated', 'Operational alert updated'), ('operational_alert.acknowledged', 'Operational alert acknowledged'), ('operational_alert.resolved', 'Operational alert resolved'), ('operational_alert.reopened', 'Operational alert reopened'), ('operational_alert.sync', 'Operational alert sync')], max_length=80),
        ),
    ]
