# Generated by Django 6.0.6 on 2026-07-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_handoffrequest'),
        ('leads', '0001_initial'),
        ('tenants', '0002_assistantprofile_use_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('handoff_created', 'Handoff created'), ('lead_qualified', 'Lead qualified'), ('conversation_summary', 'Conversation summary'), ('all', 'All')], default='all', max_length=40)),
                ('target_url', models.URLField(max_length=500)),
                ('secret_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('dry_run', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('handoff_created', 'Handoff created'), ('lead_qualified', 'Lead qualified'), ('conversation_summary', 'Conversation summary'), ('all', 'All')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dry_run', 'Dry run'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('payload_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_handoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_delivery_logs', to='conversations.handoffrequest')),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_delivery_logs', to='leads.leaddraft')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs', to='tenants.tenant')),
                ('webhook_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='integrations.tenantwebhookconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
