# Generated by Django 6.0.6 on 2026-07-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('tenants', '0006_tenantallowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('lead.qualified', 'Lead qualified'), ('handoff.created', 'Handoff created'), ('conversation.summary_ready', 'Conversation summary ready')], max_length=80)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('deduplication_key', models.CharField(max_length=220)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('retry', 'Retry'), ('dead_letter', 'Dead letter'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('available_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['available_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='integration_status_6bce69_idx'), models.Index(fields=['tenant', 'status'], name='integration_tenant__ba26f4_idx'), models.Index(fields=['event_type', 'status'], name='integration_event_t_a290d4_idx'), models.Index(fields=['created_at'], name='integration_created_9c832e_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='integration_aggrega_c8a3fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('deduplication_key',), name='unique_outbox_deduplication_key')],
            },
        ),
    ]
