# Generated by Django 6.0.6 on 2026-07-31 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_assistantprofile_business_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('chat_completion', 'Chat completion'), ('grounded_synthesis', 'Grounded synthesis'), ('embedding', 'Embedding')], max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('success', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='assistant_c_tenant__f08a49_idx'), models.Index(fields=['operation', 'created_at'], name='assistant_c_operati_ecac99_idx')],
            },
        ),
    ]
